#!/usr/bin/python3
# requires python3-pyqt5 package
# TODO: see git log -p screen.ch when communication was done via pipes and find out how to redraw
# QLabel so that exercise 13.24 from METAFONTbook will work
# (I deleted that from screen.ch because 'mf cmr10' worked slowly, for example, but now I realize
# that 'mf+ cmr10' or 'mf- cmr10' must be used instead - there envvar screen_size is not set)
# FIXME: find confirmation in pyqt5 documentation that coordinates are from upper-left to bottom-right
import sys
import mmap
import os
f=open('/dev/null','w'); os.dup2(f.fileno(),2); f.close()

# send SIGTERM to other processes with the same name
current_pid = os.getpid()
with open('/proc/' + str(current_pid) + '/status', 'r') as f: c = f.readline()
for e in os.listdir('/proc'):
  if not e.isdigit(): continue
  pid = int(e)
  if pid == current_pid: continue
  try:
    with open('/proc/' + str(pid) + '/status', 'r') as f:
      if f.readline() != c: continue
      os.kill(pid, 15)
  except Exception: pass

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
width, height = map(int, os.environ.get('screen_size').split('x'))
mm = mmap.mmap(0, width*height*4)
app = QApplication(sys.argv)
qImg = QImage(mm,width,height,width*4,QImage.Format_RGB32)
pixmap01 = QPixmap.fromImage(qImg)
pixmap_image = QPixmap(pixmap01)
label_imageDisplay = QLabel()
label_imageDisplay.setPixmap(pixmap_image)
#label_imageDisplay.setAlignment(Qt.AlignCenter)
label_imageDisplay.showMaximized()
sys.exit(app.exec_())
