#!/usr/bin/python3
# https://stackoverflow.com/questions/42570214/displaying-image-using-a-label
# requires 'python3-pyqt5' package
import sys
import mmap
import os
import signal

# destroy online display(s), which were created by mf, which finished execution previously
current_pid = os.getpid()
with open('/proc/' + str(current_pid) + '/status', 'r') as f: c = f.readline()
for e in os.listdir('/proc'):
  if not e.isdigit(): continue
  pid = int(e)
  if pid == current_pid: continue
  try:
    with open('/proc/' + str(pid) + '/status', 'r') as f:
      if f.readline() != c: continue
      for line in f:
        if line.startswith('PPid:'):
          parent_pid = line.split(':')[1].strip()
          break
  except Exception: continue
  with open('/proc/' + str(parent_pid) + '/status', 'r') as f:
    if f.readline().split(':')[1].strip() != 'virmf':
      os.kill(pid, signal.SIGTERM)

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
f=open('/dev/null','w'); os.dup2(f.fileno(),2); f.close()
width, height = map(int, os.environ.get('screen_size').split('x'))
mm = mmap.mmap(0, width*height*4)
app = QApplication(sys.argv)
qImg = QImage(mm,width,height,width*4,QImage.Format_RGB32)
pixmap01 = QPixmap.fromImage(qImg)
pixmap_image = QPixmap(pixmap01)
label_imageDisplay = QLabel()
label_imageDisplay.setPixmap(pixmap_image)
label_imageDisplay.setAlignment(Qt.AlignCenter)
label_imageDisplay.setScaledContents(True)
label_imageDisplay.setMinimumSize(width,height)
label_imageDisplay.showMinimized()
sys.exit(app.exec_())
