#!/usr/bin/python3
# https://stackoverflow.com/questions/42570214/displaying-image-using-a-label
# requires python3-pyqt5 package
import sys
import mmap
import os
f=open('/dev/null','w'); os.dup2(f.fileno(),2); f.close()

# send SIGTERM to other processes with the same name
current_pid = os.getpid()
with open('/proc/' + str(current_pid) + '/status', 'r') as f: c = f.readline()
for e in os.listdir('/proc'):
  if not e.isdigit(): continue
  pid = int(e)
  if pid == current_pid: continue
  try:
    with open('/proc/' + str(pid) + '/status', 'r') as f:
      if f.readline() != c: continue
      os.kill(pid, 15)
  except Exception: pass

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
width, height = map(int, os.environ.get('screen_size').split('x'))
mm = mmap.mmap(0, width*height*4)
app = QApplication(sys.argv)
qImg = QImage(mm,width,height,width*4,QImage.Format_RGB32)
pixmap01 = QPixmap.fromImage(qImg)
pixmap_image = QPixmap(pixmap01)
label_imageDisplay = QLabel()
label_imageDisplay.setPixmap(pixmap_image)
#print(app.primaryScreen().availableGeometry())
#label_imageDisplay.setGeometry(...)
#import time
#time.sleep(.1) # set this to mnimal value that window will not blink for 'mf cmr10'
label_imageDisplay.showMaximized()
sys.exit(app.exec_())
